### ISSUE TITLE
track error

### ISSUE THREAD

**Issue by cruix89** [RandomNinjaAtk/docker-amd#49]
is this error known? something that can be solved? thanks

INFO:deemix:[The Isley Brothers - Move Over and Let Me Dance] Getting the tags
INFO:deemix:[The Isley Brothers - Move Over and Let Me Dance] Fallback to lower bitrate
INFO:deemix:[The Isley Brothers - Move Over and Let Me Dance] Getting the album cover
INFO:deemix:[The Isley Brothers - Move Over and Let Me Dance] Downloading the track
WARNING:deemix:[The Isley Brothers - Move Over and Let Me Dance] Track not available, searching for alternative
ERROR:deemix:[The Isley Brothers - Move Over and Let Me Dance] {"REQUEST_ERROR": "Wrong parameters"}
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 490, in downloadMusic
    self.streamTrack(stream, track)
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 651, in streamTrack
    request.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://e-cdns-proxy-b.dzcdn.net/mobile/1/41f7267184fa67540288fdcd4c69f42dfc97b3737fd49a79b16e574071d8db9aecfe4e8b48f2f0fdfc315d1c6304498fccc2cf9d012e1ba86770ffad10e788166f57e4c04351018eec7420dda57d3fa5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 716, in downloadWrapper
    result = self.download(trackAPI_gw)
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 546, in download
    raise e
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 544, in download
    trackDownloaded = downloadMusic(track, trackAPI_gw)
  File "/usr/lib/python3.8/site-packages/deemix/app/downloadjob.py", line 506, in downloadMusic
    newTrack = self.dz.gw.get_track_with_fallback(searchedId)
  File "/usr/lib/python3.8/site-packages/deezer/gw.py", line 348, in get_track_with_fallback
    body = self.get_track(sng_id)
  File "/usr/lib/python3.8/site-packages/deezer/gw.py", line 95, in get_track
    return self.api_call('song.getData', {'sng_id': sng_id})
  File "/usr/lib/python3.8/site-packages/deezer/gw.py", line 78, in api_call
    raise APIError(json.dumps(result_json['error']))
deezer.gw.APIError: {"REQUEST_ERROR": "Wrong parameters"}

**Comment by RandomNinjaAtk** [comment]
This most likely is an issue with the DL client, you need to report it there instead of here....
