### ISSUE TITLE
Downloads broken

### ISSUE THREAD

**Issue by 0xE28891** [RandomNinjaAtk/docker-amd#55]
I believe the recent changes at Deezer have broken the ability to download or the d**mix needs to be updated.

I can download FLAC successfully using the latest standalone version of d**mix.

**Comment by 0xE28891** [comment]
Pulling the latest version of the docker image, the following error is occurring: 

```
/usr/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/scripts/dlclient.py", line 8, in <module>
    from deemix.app import deemix
ModuleNotFoundError: No module named 'deemix.app'

```

**Comment by rouggy** [comment]
since the update of deemix it is indeed broken, I really hope it will be updated :(

**Comment by 0xE28891** [comment]
> 
> 
> Pulling the latest version of the docker image, the following error is occurring:
> 
> ```
> /usr/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> Traceback (most recent call last):
>   File "/scripts/dlclient.py", line 8, in <module>
>     from deemix.app import deemix
> ModuleNotFoundError: No module named 'deemix.app'
> ```

requests dependency warning is now fixed. However, "ModuleNotFoundError: No module named 'deemix.app'" is still an issue.

**Comment by acherifi** [comment]
Same error on my side

**Comment by RandomNinjaAtk** [comment]
I don't have time to work on this, help wanted...

**Comment by whatsthestoryglory** [comment]
Apologies in advance, I'm not the most well versed in this stuff, just poking at it until something works...  These might all be stupid ideas.

At first it looks like the issue here is with the `pycryptodomex` package.  Trying to run `pip wheel --wheel-dir=/root/wheels deemix` manually inside the container gives an error about needing gcc.

```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -Isrc/ -I/usr/include/python3.8 -c src/MD2.c -o build/temp.linux-x86_64-3.8/src/MD2.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycryptodomex
```

I then ran `apk add gcc` which got past the initial error, but then gave a new error about `stdio.h`.  I then ran `apk add musl-dev`  after which `pip wheel --wheel-dir=/root/wheels deemix` finally installed okay.  So, adding `gcc` and `musl-dev` to your dockerfile should get `deemix` installed properly now.

Unfortunately, that still doesn't work.  `dlclient.py` still fails with `ModuleNotFoundError: No module named 'deemix.app'`.  

Now it looks like the problem is the refactoring that deemix-py went through.  Somewhere around [this commit](https://git.freezer.life/RemixDev/deemix-py/commit/f530a4e89f930fb36db2ee2b9a4454bce825d3c9), where I noticed they removed the /app directory where the `deemix` class being imported in `dlclient.py` existed.

Looks to my highly uneducated eye that some refactoring will be required for `dlclient.py`.  Could try re-implementing deezer.app from before the refactoring [here](https://git.freezer.life/RemixDev/deemix-py/src/commit/67fcb7d37f0cd24564b7ff2738cd5e69551edc6d/deemix/app/__init__.py) or, probably the better option, refactor the `dlclient.py` code to match the changes deemix implemented.

Sorry I can't be of more help (yet...)

**Comment by daPyr0x** [comment]
Apologies in advance, I'm not the most well versed in this stuff, just poking at it until something works...  These might all be stupid ideas.

At first it looks like the issue here is with the `pycryptodomex` package.  Trying to run `pip wheel --wheel-dir=/root/wheels deemix` manually inside the container gives an error about needing gcc.

```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -Isrc/ -I/usr/include/python3.8 -c src/MD2.c -o build/temp.linux-x86_64-3.8/src/MD2.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycryptodomex
```

I then ran `apk add gcc` which got past the initial error, but then gave a new error about `stdio.h`.  I then ran `apk add musl-dev`  after which `pip wheel --wheel-dir=/root/wheels deemix` finally installed okay.  So, adding `gcc` and `musl-dev` to your dockerfile should get `deemix` installed properly now.

Unfortunately, that still doesn't work.  `dlclient.py` still fails with `ModuleNotFoundError: No module named 'deemix.app'`.  

Now it looks like the problem is the refactoring that deemix-py went through.  Somewhere around [this commit](https://git.freezer.life/RemixDev/deemix-py/commit/f530a4e89f930fb36db2ee2b9a4454bce825d3c9), where I noticed they removed the /app directory where the `deemix` class being imported in `dlclient.py` existed.

Looks to my highly uneducated eye that some refactoring will be required for `dlclient.py`.  Could try re-implementing deezer.app from before the refactoring [here](https://git.freezer.life/RemixDev/deemix-py/src/commit/67fcb7d37f0cd24564b7ff2738cd5e69551edc6d/deemix/app/__init__.py) or, probably the better option, refactor the `dlclient.py` code to match the changes deemix implemented.

Sorry I can't be of more help (yet...)

**Comment by cruix89** [comment]
hi guys, sorry for insert a stupid comment so, we need create a team of programers to support theprojects of our friend @RandomNinjaAtk 
him projects is great and we dont allow them dying.

i think so all help is welcome, i dont know nothing about programmer but i start to learn righ now, in some time i can contribute something.

I ask you to bring all the help you can, friends, relatives, etc. who know how to program

thank you guys
