### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Wokjak69** [RandomNinjaAtk/docker-amd#69]
**Getting this error message pass few days, I refreshed my ARL but that didn't fix anything**

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 467, in downloadWrapper
result = self.download(extraData, track)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 286, in download
selectedFormat = getPreferredBitrate(File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 158, in getPreferredBitrate
url = getCorrectURL(currentTrack, formatName, formatNumber)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 115, in getCorrectURL
url = dz.get_track_url(track.trackToken, formatName)
File "/usr/lib/python3.8/site-packages/deezer/init.py", line 142, in get_track_url
tracks = self.get_tracks_url([track_token, ], track_format)
File "/usr/lib/python3.8/site-packages/deezer/init.py", line 187, in get_tracks_url
result.append(data['media'][0]['sources'][0]['url'])

**Comment by Wokjak69** [comment]
how'd i tell which version?

**Comment by RandomNinjaAtk** [comment]
At the start of the script, it should give a version

**Comment by Wokjak69** [comment]
says i'm on SCRIPT VERSION 1.5.48

**Comment by RandomNinjaAtk** [comment]
The latest is: 1.5.481
https://github.com/RandomNinjaAtk/docker-amd/commit/4cfebe944ffcabec89b74b12c2f73ef6252a7390

Try updating, see if that helps.

**Comment by Wokjak69** [comment]
i pulled the latest image

**Comment by Wokjak69** [comment]
okay it finally pulled to latest version now
