### ISSUE TITLE
Error back :( i'm using 1.5.481

### ISSUE THREAD

**Issue by Slackerjacker** [RandomNinjaAtk/docker-amd#70]
tracks = self.get_tracks_url([track_token, ], track_format)
File "/usr/lib/python3.8/site-packages/deezer/__init__.py", line 187, in get_tracks_url
result.append(data['media'][0]['sources'][0]['url'])
IndexError: list index out of range
Paul Wall - Break Bread (Chopped & Screwed) list index out of range
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 467, in downloadWrapper
result = self.download(extraData, track)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 286, in download
selectedFormat = getPreferredBitrate(
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 158, in getPreferredBitrate
url = getCorrectURL(currentTrack, formatName, formatNumber)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 115, in getCorrectURL
url = dz.get_track_url(track.trackToken, formatName)
File "/usr/lib/python3.8/site-packages/deezer/__init__.py", line 142, in get_track_url
tracks = self.get_tracks_url([track_token, ], track_format)
File "/usr/lib/python3.8/site-packages/deezer/__init__.py", line 187, in get_tracks_url
result.append(data['media'][0]['sources'][0]['url'])
IndexError: list index out of range

**Comment by Eldarock** [comment]
Same here :)

2022-01-05 15:55:53 :: 10 of 2164 :: Aphex Twin :: 1993 :: EP :: On :: DOWNLOADING :: On :: https://deezer.com/album/2796581...
Aphex Twin - 73-Yips list index out of range
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 467, in downloadWrapper
result = self.download(extraData, track)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 286, in download
selectedFormat = getPreferredBitrate(
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 158, in getPreferredBitrate
url = getCorrectURL(currentTrack, formatName, formatNumber)
File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 115, in getCorrectURL
url = dz.get_track_url(track.trackToken, formatName)
File "/usr/lib/python3.8/site-packages/deezer/__init__.py", line 149, in get_track_url
tracks = self.get_tracks_url([track_token, ], track_format)
File "/usr/lib/python3.8/site-packages/deezer/__init__.py", line 194, in get_tracks_url
result.append(data['media'][0]['sources'][0]['url'])
IndexError: list index out of range

**Comment by RandomNinjaAtk** [comment]
Looks like you need to update... a new version should be being built now...

**Comment by Eldarock** [comment]
Looks like i have differents errors now :

https://pastebin.com/MAF4tQY7

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
