### ISSUE TITLE
AMD only downloading cutoff list not missing list

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/docker-amd#76]
I've tried forcing it by changing it to missing only and the script immediately fails when it tries to pull the missing albums, finding missing albums 0 found despite having plenty in lidarrs wanted tab.
jq: error: could not open file /scripts/temp-lidarr-*.json: no such file or directory.

I think the error is related to this in lidarrs logs 
```
[v0.8.1.2135] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Lidarr.Api.V1.Albums.AlbumResourceMapper.ToResource(Album model) in D:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumResource.cs:line 59
   at Lidarr.Api.V1.Albums.AlbumModuleWithSignalR.MapToResource(Album album, Boolean includeArtist) in D:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumModuleWithSignalR.cs:line 73
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Lidarr.Http.LidarrRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in D:\a\1\s\src\Lidarr.Http\LidarrRestModule.cs:line 46
   at Lidarr.Api.V1.Wanted.MissingModule.GetMissingAlbums(PagingResource`1 pagingResource) in D:\a\1\s\src\Lidarr.Api.V1\Wanted\MissingModule.cs:line 48
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

```

I know my compose is good as it pulls the cutoff list and downloads them just fine and lidarr imports those so the mapping is correct. It just seems odd that it works for cutoff and not missing.

Lidarr version 0.8.1.2135 also in docker on the same system. AMD is the latest version.

Updating lidarr to the latest nightly (1.0.0.2458) gives the same error

**Comment by Glynax** [comment]
I've narrowed it down to lidarr being.. broken. Kid rock, puscifer and 6ix9ine weren't loading properly like I could open them but it gave an error instead of albums or anything. Deleted them. Readded them. AMD now seems to be working properly. Can we get some error checking on it besides it just saying it couldn't create the script? Took forever to hunt down why this was busted.
