### ISSUE TITLE
json.decoder.JSONDecodeError for every album

### ISSUE THREAD

**Issue by ImjuzCY** [RandomNinjaAtk/docker-amd#84]
Logs:

```
2022-03-03 17:38:29 :: 48 of 135 :: Meghan Trainor :: 2020 :: Album :: A Very Trainor Christmas :: SEARCHING...
2022-03-03 17:38:29 :: 48 of 135 :: Meghan Trainor :: 2020 :: Album :: A Very Trainor Christmas :: DOWNLOADING :: A Very Trainor Christmas (Deluxe) :: https://deezer.com/album/267241542...
Traceback (most recent call last):
  File "/scripts/dlclient.py", line 45, in <module>
    download()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/deemix/__main__.py", line 107, in download
    downloadLinks(url, bitrate)
  File "/usr/lib/python3.8/site-packages/deemix/__main__.py", line 75, in downloadLinks
    downloadObject = generateDownloadObject(dz, link, bitrate, plugins, listener)
  File "/usr/lib/python3.8/site-packages/deemix/__init__.py", line 66, in generateDownloadObject
    return generateAlbumItem(dz, link_id, bitrate)
  File "/usr/lib/python3.8/site-packages/deemix/itemgen.py", line 72, in generateAlbumItem
    albumAPI_gw_page = dz.gw.get_album_page(link_id)
  File "/usr/lib/python3.8/site-packages/deezer/gw.py", line 108, in get_album_page
    return self.api_call('deezer.pageAlbum', {
  File "/usr/lib/python3.8/site-packages/deezer/gw.py", line 42, in api_call
    result_json = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-03-03 17:38:30 :: 48 of 135 :: Meghan Trainor :: 2020 :: Album :: A Very Trainor Christmas :: DOWNLOAD :: ERROR :: No files found
```` 

The same thing happens for every album it tries to download. Deemix's problem?

**Comment by ImjuzCY** [comment]
Found out my ARL is invalid. Solved it by changing it.
